### ISSUE TITLE
Memory leaks with continue updated input data

### ISSUE THREAD

**Issue by eeyshen** [vega/vega-embed#270] opened 2019-11-16 08:38 UTC
These is memory leaks with vega-embed. For example, with following example, by clicking button update. The memory used keeps increasing. Is there any way to solve it? Thanks.
```html
<!DOCTYPE html>
<head>
  <meta charset="utf-8" />
  <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.0.0-beta.2"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@5"></script>
</head>

<body>
  <div id="vis"></div>

  <script>
    const spec1 = {
      $schema: "https://vega.github.io/schema/vega-lite/v3.json",
      description: "A simple bar chart with embedded data.",
      width: 360,
      data: {
        values: [
          { a: "A", b: 28 },
          { a: "B", b: 55 },
          { a: "C", b: 43 },
          { a: "D", b: 91 },
          { a: "E", b: 81 },
          { a: "F", b: 53 },
          { a: "G", b: 19 },
          { a: "H", b: 87 },
          { a: "I", b: 52 }
        ]
      },
      mark: "bar",
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" },
        tooltip: { field: "b", type: "quantitative" }
      }
    };
    const spec2 = {
      $schema: "https://vega.github.io/schema/vega-lite/v3.json",
      description: "A simple bar chart with embedded data.",
      width: 500,
      data: {
        values: [
          { a: "A", b: 33 },
          { a: "B", b: 32 },
          { a: "C", b: 16 },
          { a: "D", b: 28 },
          { a: "E", b: 35 },
          { a: "F", b: 81 },
          { a: "G", b: 90 },
          { a: "H", b: 10 },
          { a: "I", b: 5 }
        ]
      },
      mark: "bar",
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" },
        tooltip: { field: "b", type: "quantitative" }
      }
    };
    let spec = spec1;
    function myFunction() {
      setInterval(function() {
        if (spec === spec1) spec = spec2;
        else spec = spec1;

        vegaEmbed("#vis", spec)
          .then()
          .catch(console.warn);
      }, 1000);
    }
  </script>

  <button onclick="myFunction()">Update</button>
</body>
```

**Comment by domoritz** [comment] 2019-11-17 03:26
In order to free resources when they are not needed anymore, you need to call `view.finalize`. Here is the updated code for your example

```html
<!DOCTYPE html>
<head>
  <meta charset="utf-8" />
  <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.0.0-beta.2"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@5"></script>
</head>

<body>
  <div id="vis"></div>

  <script>
    const spec1 = {
      $schema: "https://vega.github.io/schema/vega-lite/v4.json",
      width: 360,
      data: {
        values: [
          { a: "A", b: 28 },
          { a: "B", b: 55 },
          { a: "C", b: 43 },
          { a: "D", b: 91 },
          { a: "E", b: 81 },
          { a: "F", b: 53 },
          { a: "G", b: 19 },
          { a: "H", b: 87 },
          { a: "I", b: 52 }
        ]
      },
      mark: "bar",
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" },
        tooltip: { field: "b", type: "quantitative" }
      }
    };
    const spec2 = {
      $schema: "https://vega.github.io/schema/vega-lite/v4.json",
      description: "A simple bar chart with embedded data.",
      width: 500,
      data: {
        values: [
          { a: "A", b: 33 },
          { a: "B", b: 32 },
          { a: "C", b: 16 },
          { a: "D", b: 28 },
          { a: "E", b: 35 },
          { a: "F", b: 81 },
          { a: "G", b: 90 },
          { a: "H", b: 10 },
          { a: "I", b: 5 }
        ]
      },
      mark: "bar",
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" },
        tooltip: { field: "b", type: "quantitative" }
      }
    };
    let spec = spec1;
    let view;

    function myFunction() {
      setInterval(function() {
        if (spec === spec1) spec = spec2;
        else spec = spec1;
        
        if (view) {
           view.finalize();
        }

        vegaEmbed("#vis", spec)
          .then(function(result) {
          // save view so we can finalize it
          	view = result.view;
        	})
          .catch(console.warn);
      }, 1000);
    }
  </script>

  <button onclick="myFunction()">Update</button>
</body>
```

**Comment by domoritz** [comment] 2019-11-17 03:27
The cleaner (and faster) solution is to use the view API instead. I'll leave this as an exercise for the reader ;-)

https://vega.github.io/vega/docs/api/view/

**Comment by eeyshen** [comment] 2019-11-17 08:03
Thanks. How I get it done with react-vega?

**Comment by eeyshen** [comment] 2019-11-17 08:10
I tried the updated code. But the memory is still increasing.

**Comment by domoritz** [comment] 2019-11-17 08:11
How are you tracking memory usage? can you use the browser memory debugger? It should also show who is holding on to memory.

**Comment by eeyshen** [comment] 2019-11-17 08:21
I only open one tab in chrome, that runs the example above. Do not do anything else with the chrome. Keep looking at the process named "Google Chrome Helper (GPU)". It is found that it keeps increasing, from hundreds MB to several GBs.

**Comment by domoritz** [comment] 2019-11-17 08:28
Can you find out what's holding on to the memory?

**Comment by eeyshen** [comment] 2019-11-17 08:33
I debug the problem with Chrome Task Manager. I found the memory used the tab keep increasing slowly. But the task named "GPU Process" keeps increasing markedly.

**Comment by eeyshen** [comment] 2019-11-17 08:35
The performance look as follows:
<img width="2550" alt="截屏2019-11-17下午4 34 10" src="https://user-images.githubusercontent.com/31716017/69005116-1d34e800-0958-11ea-9d6d-6ff719a2f02d.png">

**Comment by domoritz** [comment] 2019-11-17 08:35
The listeners should get deleted on `finalize` but somehow the number keeps increasing. I have to dig more into this tomorrow. 

<img width="1128" alt="Screen Shot 2019-11-17 at 00 34 42" src="https://user-images.githubusercontent.com/589034/69005120-12d00b00-08d2-11ea-95d9-2c0cd61bcb81.png">

**Comment by eeyshen** [comment] 2019-11-17 08:37
Thanks.

**Comment by eeyshen** [comment] 2019-11-18 10:19
Do you find why the memory leaks happen?

**Comment by domoritz** [comment] 2019-11-19 05:54
No, I didn't have time to look yet.

**Comment by eeyshen** [comment] 2019-11-25 03:02
Is there someone still take care of this problem? I believe it is an important problem for practical usage of vega-embed and related vega, vega-lite. I would like to help. Would anyone give some tip for how to debug and challenge this problem? Thanks.

**Comment by domoritz** [comment] 2019-11-26 02:29
I've been swamped with other requests but completely agree that this is an important issue to look into. What I'm curious about is what objects are holding onto memory that may not need to. I'd use the browser memory debugger to do that.

**Comment by domoritz** [comment] 2019-11-26 20:15
Looks like the culprit is Vega-Embed. Without Vega-Embed, memory consumption stays low. I think the problem may be the event handlers. Let me try to fix it. 

<img width="1094" alt="Screen Shot 2019-11-26 at 12 14 16" src="https://user-images.githubusercontent.com/589034/69669232-4fc09e00-1046-11ea-80cf-1bcb77d85808.png">

**Comment by domoritz** [comment] 2019-11-26 21:32
Fixed in https://github.com/vega/vega-embed/pull/280

**Closed** 2019-11-26 21:31 UTC

**Comment by eeyshen** [comment] 2019-11-27 01:03
Great. Looking forward to the next release.

**Comment by eeyshen** [comment] 2020-05-18 01:21
I believe the problem appear again. The screenshot below show the memory profile of the example above.
```
<!DOCTYPE html>
<head>
  <meta charset="utf-8" />
  <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.12.1"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
</head>

<body>
  <div id="vis"></div>

  <script>
    const spec1 = {
      $schema: "https://vega.github.io/schema/vega-lite/v4.json",
      description: "A simple bar chart with embedded data.",
      width: 360,
      data: {
        values: [
          { a: "A", b: 28 },
          { a: "B", b: 55 },
          { a: "C", b: 43 },
          { a: "D", b: 91 },
          { a: "E", b: 81 },
          { a: "F", b: 53 },
          { a: "G", b: 19 },
          { a: "H", b: 87 },
          { a: "I", b: 52 }
        ]
      },
      mark: "bar",
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" },
        tooltip: { field: "b", type: "quantitative" }
      }
    };
    const spec2 = {
      $schema: "https://vega.github.io/schema/vega-lite/v4.json",
      description: "A simple bar chart with embedded data.",
      width: 500,
      data: {
        values: [
          { a: "A", b: 33 },
          { a: "B", b: 32 },
          { a: "C", b: 16 },
          { a: "D", b: 28 },
          { a: "E", b: 35 },
          { a: "F", b: 81 },
          { a: "G", b: 90 },
          { a: "H", b: 10 },
          { a: "I", b: 5 }
        ]
      },
      mark: "bar",
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" },
        tooltip: { field: "b", type: "quantitative" }
      }
    };
    let spec = spec1;
    function myFunction() {
      setInterval(function() {
        if (spec === spec1) spec = spec2;
        else spec = spec1;

        vegaEmbed("#vis", spec)
          .then()
          .catch(console.warn);
      }, 1000);
    }
  </script>

  <button onclick="myFunction()">Update</button>
</body>
```
![截屏2020-05-18 上午9 17 01](https://user-images.githubusercontent.com/31716017/82165718-c00af680-98e8-11ea-9392-8a7fc00bcd10.png)

**Comment by domoritz** [comment] 2020-05-18 01:49
Please finalize the embed result as described in the docs.

**Comment by eeyshen** [comment] 2020-05-18 02:08
We use react-vega, which calls finalize as follows. Is there something we should do more? Thank.
```
  clearView() {
    this.modifyView(view => {
      view.finalize();
    });
    this.viewPromise = undefined;

    return this;
  }
```

**Comment by domoritz** [comment] 2020-05-18 03:04
I don't know how this fits into the react lifecycle. However, your example above does not contain finalize. Can you add finalize to see whether it fixes the issue? If yes, then we know the problem is in react vega. 

Thanks for your help!

**Comment by eeyshen** [comment] 2020-05-18 07:48
I tried to call finalize as follows. And the memory cost show as the screenshot image.
```
<!DOCTYPE html>
<head>
  <meta charset="utf-8" />
  <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.12.1"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
</head>

<body>
  <div id="vis"></div>

  <script>
    const spec1 = {
      $schema: "https://vega.github.io/schema/vega-lite/v3.json",
      description: "A simple bar chart with embedded data.",
      width: 360,
      data: {
        values: [
          { a: "A", b: 28 },
          { a: "B", b: 55 },
          { a: "C", b: 43 },
          { a: "D", b: 91 },
          { a: "E", b: 81 },
          { a: "F", b: 53 },
          { a: "G", b: 19 },
          { a: "H", b: 87 },
          { a: "I", b: 52 }
        ]
      },
      mark: "bar",
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" },
        tooltip: { field: "b", type: "quantitative" }
      }
    };
    const spec2 = {
      $schema: "https://vega.github.io/schema/vega-lite/v3.json",
      description: "A simple bar chart with embedded data.",
      width: 500,
      data: {
        values: [
          { a: "A", b: 33 },
          { a: "B", b: 32 },
          { a: "C", b: 16 },
          { a: "D", b: 28 },
          { a: "E", b: 35 },
          { a: "F", b: 81 },
          { a: "G", b: 90 },
          { a: "H", b: 10 },
          { a: "I", b: 5 }
        ]
      },
      mark: "bar",
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" },
        tooltip: { field: "b", type: "quantitative" }
      }
    };
    let spec = spec1;
    function myFunction() {
      setInterval(function() {
        if (spec === spec1) spec = spec2;
        else spec = spec1;

        vegaEmbed("#vis", spec)
          .then(function(res){
          	res.finalize();
          })
          .catch(console.warn);
      }, 1000);
    }
  </script>

  <button onclick="myFunction()">Update</button>
</body>
```
<img width="1800" alt="截屏2020-05-18 下午3 22 10" src="https://user-images.githubusercontent.com/31716017/82187077-7210e580-991e-11ea-97df-24b53b64c9cb.png">

**Comment by domoritz** [comment] 2020-05-18 15:13
That’s good, right?

**Comment by eeyshen** [comment] 2020-05-19 09:08
Yes. I proposed an issue for react-vega.

**Comment by brandon-marginalunit** [comment] 2020-05-22 20:56
We're having what I think may be the same problem too; the difference for us is that we aren't using `react-vega` nor `vega-embed`. We're creating a new `View` directly, and then updating it via `view.data("foo", [ ... ]).runAsync()`.

Since we aren't creating a new `Vega` instance each time, or using a fresh config each time, I don't think the `.finalize()` mitigation applies to us (please correct me if I'm wrong). From looking at the memory profiler, it seems like a bunch of detached SVG group elements are not being released by Vega:

<img width="492" alt="DevTools_-_muse-dev_local_8090_" src="https://user-images.githubusercontent.com/65309790/82708800-bf55c580-9c44-11ea-98bd-9bfe5aa06ad9.png">

Unfortunately I don't have a clean minimal-reproduction example.

**Comment by domoritz** [comment] 2020-05-23 02:49
Can you try to reproduce the issue with a small example and file an issue with Vega directly?

**Comment by eeyshen** [comment] 2020-05-26 09:52
Is there any plan to update react-vega to fix the problem? Or else is there any way to use vega-embed with react directly?

**Comment by brandon-marginalunit** [comment] 2020-05-26 16:01
@domoritz I can file with Vega directly, but I'm not sure I have time to narrow it down to a small example. I'll see what I can do.

**Comment by domoritz** [comment] 2020-05-26 17:02
> Or else is there any way to use vega-embed with react directly?

That's easily possible with a reference. Something like this:

```
class Vega {
  componentDidMount() {
    var embed = await vegaEmbed(this.refs.vis, spec);
  }

  render() {
    return (
      <div ref="vis" />
    );
  }
}
```

You may also be interested in https://github.com/vega/vega/pull/2652

**Comment by eeyshen** [comment] 2020-05-27 06:25
> You may also be interested in [vega/vega#2652](https://github.com/vega/vega/pull/2652)

Is the memory leak caused by the Vega caches?

**Comment by jheer** [comment] 2020-05-27 08:42
Memory leaks could arise from multiple sources:

1. Creating multiple visualizations (new View instances) without calling `finalize` on the old View instances.
2. Using streaming data that involves nested specifications (basically, `group` marks), in which deleted data leads to deleted groups with content that remains in caches.

PR vega/vega#2652 should fix number 2 above. Number 1 needs to be addressed by developer code (or in libraries such as vega-embed or vega-react).

**Comment by eeyshen** [comment] 2020-05-27 08:57
The memory leaks still happen while react-vega calls finalize. Is it caused by number 2 above?
