### ISSUE TITLE
actions menu: documentClickHandler is not removed

### ISSUE THREAD

**Issue by pelikhan** [vega/vega-embed#733] opened 2021-08-04 17:33 UTC
This is an issue that arised while using react-vega so it might have to be moved upstream.

There is a memory leak in the registeration of the actions mmenu. The document click handler is registered everytime the spec or data buffer is updated in react-vega; and it won't be garbage collected.

https://github.com/vega/vega-embed/blob/641b65e1bcbaaf2a2b70c783fc0fe1bdfb825d6e/src/embed.ts#L434

Thank you for this great project!

**Comment by domoritz** [comment] 2021-08-05 04:44
Is this https://github.com/vega/react-vega/issues/383?

**Comment by pelikhan** [comment] 2021-08-05 04:49
I tried to trace where documentClickHandler would be removed but could not find suck code. So I think it is not related.

**Comment by domoritz** [comment] 2021-08-05 04:52
I'm not following. I think the issue is in react vega, not embed. Do you agree?

**Comment by pelikhan** [comment] 2021-08-05 10:21
I think this issue is not limited to react-embed. Vega registers an event callback on  the document DOM element and does not provide a way to « unmount » it. Since the callback references various Vega objects in its closure, the garbage collector cannot reclaim them.

My code using react-Vega happened to exacerbated this issue because I had a bug that mutated the spec JSON multiple times per second…
________________________________

**Comment by domoritz** [comment] 2021-08-05 13:11
Vega view has a finalize method that should clean that up. If it doesn't, please file an issue with a reproduction in Vega. 

I'll close the issue here for now as I don't think embed has a bug.

**Closed by domoritz** 2021-08-05 13:11 UTC

**Comment by pelikhan** [comment] 2021-08-05 13:18
If i am not mistakened, the callback is created by vega-embed and added to the document click handlers. I don't see how vega finalize would be able to clean up this callback.

It is declared in this scope at
https://github.com/vega/vega-embed/blob/641b65e1bcbaaf2a2b70c783fc0fe1bdfb825d6e/src/embed.ts#L413
and added to document.click at
https://github.com/vega/vega-embed/blob/641b65e1bcbaaf2a2b70c783fc0fe1bdfb825d6e/src/embed.ts#L434

**Comment by domoritz** [comment] 2021-08-05 13:37
Embed has its own finalize that you need to call.
