### ISSUE TITLE
Tooltips on hover in responsive chart don't seem to work properly on mobile devices

### ISSUE THREAD

**Issue by armsp** [vega/vega-embed#432] opened 2020-05-10 11:15 UTC
I used altair to generate a [chloropleth map](https://armsp.github.io/covid19-viz/india/index.html) and embed it in a webpage. It works perfectly as expected. However to make it responsive on smaller screens I used the css solution below since nothing from altair itself was working -
```css
canvas.marks {
    max-width: 100%!important;
    height: auto!important;
}
```
Now it is responsive but it works well only on Laptops and larger screens. If you open it in mobile you will feel like the canvas has not resized at all....meaning if you click anywhere on top region no tooltip will appear but if you click on the empty region on bottom right then tooltips will appear and the states are al wrong, moreover tooltip should not appear in empty regions.

Any idea how to fix this?

**Comment by domoritz** [comment] 2020-05-10 17:24
I'd try the responsive design mode in your browser to investigate the issue. 

I believe this is a duplicate of https://github.com/vega/vega-tooltip/issues/310.

**Closed by domoritz** 2020-05-10 17:24 UTC

**Comment by armsp** [comment] 2020-05-10 18:03
@domoritz Yeah, i think #310 is exactly what I am facing right now. But there doesn't seem to be any solution for it.

**Comment by domoritz** [comment] 2020-05-10 18:22
I didn't have the cycles to work on it yet. 

For your specific example, I would say try to scale the chart in Vega itself instead. You can listen to changes to the container size. Something like https://vega.github.io/editor/#/examples/vega-lite/bar_size_responsive

**Comment by armsp** [comment] 2020-05-11 04:57
@domoritz Just one clarification - how is the above example responsive? When I open the link and resize my window, the chart gets cropped. Am I missing something here?

**Comment by domoritz** [comment] 2020-05-11 06:14
I responded in the other thread.
