### ISSUE TITLE
vega-embed 6.20.4 breaks downstream package build

### ISSUE THREAD

**Issue by fcollonval** [vega/vega-embed#806] opened 2021-11-29 08:16 UTC
In JupyterLab, the application of the patch is breaking our CI. This is most certainly due to the usage of a multi packages repository.

```sh
Error: Patch file found for package yallist which is not present at node_modules/yallist
---
patch-package finished with 1 error(s).

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vega-embed@6.20.4 postinstall: `npx patch-package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vega-embed@6.20.4 postinstall script.
```

One comment on the logic, a better pattern would be to pin to a working older `yallist` version, to publish your own version of `yallist` or to wait for a patch upstream. The current approach of patching a dependency on the flight sounds pretty dangerous. Moreover this could black list you in some organization because you apply changes outside your scope.

**Comment by domoritz** [comment] 2021-11-29 16:11
Thanks for the bug report. I will look into it. 

This is strange since yallist is required by lru cache which is needed for semver (which is a direct dependency). The issue is that I cannot make my own version since yallist is not a direct dependency. The package hasn't been updated in a while and the open issue doesn't look like it will be fixed: https://github.com/isaacs/yallist/issues/22.

I'm very open to ideas.

**Comment by aju** [comment] 2021-11-29 18:27
@domoritz we have same issue with this and it break our flow -any chance to revert?

**Comment by domoritz** [comment] 2021-11-29 19:17
I don't know what to revert. We need to do the patching because otherwise we break web pack builds: https://github.com/vega/vega-embed/issues/780. My yarn is having issues this morning. I'll check on another network in a bit.

<img width="630" alt="Screen Shot 2021-11-29 at 14 16 12" src="https://user-images.githubusercontent.com/589034/143928792-a3741244-5d57-4753-b78f-b192a61bf1b4.png">

In the meantime, if someone has ideas for a fix, please let me know.

**Comment by domoritz** [comment] 2021-11-30 01:18
Welp, looks like it's being blocked by the patching script https://github.com/ds300/patch-package/issues/84. I'm not sure what to do now. Any advice is appreciated. I'll reopen #780.

**Closed** 2021-11-30 01:40 UTC

**Comment by fcollonval** [comment] 2021-11-30 07:45
Thanks a lot for quickly patching this one :heart:  Our CI is green with the latest version :tada:

**Comment by jtpio** [comment] 2021-11-30 08:55
Thanks @domoritz!

**Comment by aju** [comment] 2021-11-30 09:23
Thank you @domoritz !

**Comment by domoritz** [comment] 2021-11-30 14:25
You're all very welcome.

I sent a pull request to fix the original package but I don't know whether it'll be merged anytime soon so we may have to live with the patch.

**Comment by jrhoads** [comment] 2021-12-01 18:45
Thank you @domoritz !
