### ISSUE TITLE
Use auto height on chart-wrapper div

### ISSUE THREAD

**Issue by metasoarous** [vega/vega-embed#584] opened 2020-10-22 19:30 UTC
Hello; Thanks for your time.

I don't know when this changed, but I recently discovered that the latest `vega-*` releases automatically set `div.chart-wrapper {height: 100%}` which has the effect of leaving a large blank area underneath the visible chart area. I can customize this from [Oz](https://github.com/metasoarous/oz) via my own stylesheets, but this may catch users offguard who opt out of these styles, or presumably who are using vega outside of Oz. Please consider switching back to the previous behavior.

Thanks again!

**Comment by domoritz** [comment] 2020-10-22 20:05
@haldenl could this be the result of our recent changes?

**Comment by metasoarous** [comment] 2020-10-22 23:17
@jheer Oh! Thanks for catching that. For some reason I thought vega-embed had moved in with the vega monorepo as well. Thanks for the catch.

**Comment by domoritz** [comment] 2020-10-22 23:36
Could you try an older version of embed to see when the change was introduced?

**Comment by haldenl** [comment] 2020-10-23 20:29
ah possibly... @metasoarous would you be able to share an example or screenshot?

**Comment by domoritz** [comment] 2020-11-04 20:07
@metasoarous Can you provide an example?

**Comment by metasoarous** [comment] 2020-11-05 00:45
Yup; Thanks for the reminder. Here you go.

https://gist.github.com/metasoarous/482d6b65f0b29afc8a1621078ffc2bca

Thanks again!

**Comment by metasoarous** [comment] 2020-11-05 00:47
Here's an image of what's going on:

![image](https://user-images.githubusercontent.com/88556/98183633-6f4e8080-1ebd-11eb-9917-53e915ce74fd.png)

**Comment by haldenl** [comment] 2020-11-06 23:19
Thanks @metasoarous ! I'll take a look this weekend

**Comment by haldenl** [comment] 2020-11-09 18:22
Ok it seems like we should not apply the `width: 100%, height: 100%` styles unless 'autosize' is being used. More specifically, apply `width: 100%` if `fit` or `fit-x`, and `height: 100%` if `fit` or `fit-y`.  The problem is then that we need to read the compiled vega spec first, and `autosize` can be a signal as well....

I'm not quite sure what the use case for dynamic `autosize` is. @domoritz thoughts?

**Comment by domoritz** [comment] 2020-11-09 19:07
Autosize is documented at https://vega.github.io/vega-lite/docs/size.html#autosize. It's used for example when you want to change from bottom up to top down layout. We set it automatically for example when the chart is responsive: https://vega.github.io/vega-lite/docs/size.html#specifying-responsive-width-and-height.

**Comment by metasoarous** [comment] 2020-11-09 21:57
That makes sense to me.

Chris

**Comment by domoritz** [comment] 2021-02-22 12:05
@haldenl can you wrap up this issue so we can fix it or close it?

**Comment by domoritz** [comment] 2021-05-05 22:28
Is this still an issue? If so, please respond with details and I will reopen.

**Comment by metasoarous** [comment] 2021-05-07 23:43
I'm back on the saddle after a few months of not doing much viz work and this problem is biting me again. I searched a bit through the source code to see if I could fix this myself, and the only place I see `width` showing up was in `src/embed.ts`, and I don't see anything setting it to 100%:

https://github.com/vega/vega-embed/blob/master/src/embed.ts#L383-L393

Is there a chance that this has already been resolved in previous commit/release?

Thanks!

**Comment by domoritz** [comment] 2021-05-08 00:02
The other place that sets style properties is https://github.com/vega/vega-embed/blob/master/vega-embed.scss.

**Closed** 2021-05-10 21:14 UTC

**Comment by domoritz** [comment] 2021-05-10 21:20
Mostly fixed now as long as the autosize is not set via a signal. If this comes up again, we can add a signal listener to set the classes.

**Comment by ryan-williams** [comment] 2023-08-26 15:34
Just leaving a breadcrumb here that `{ container: 'height', autosize: { type: "fit" }, … }` /  wasn't working for me when the container's height was set using the CSS `min-height` property. I had to set the container's CSS `height` explicitly.

With `min-height` on the container, the chart was rendering with close to 0 height (24px), no matter how large the container's `min-height` (and corresponding `offsetHeight`) was.
